sudo: required
matrix:
  include:
    - language: scala
      scala: 2.12.6
      services: mongodb
      before_install:
        - cd senz-server
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test
        
    - language: python
      python: 3.6
      before_install:
        - pip install pytest
      script:
        - pytest

    - language: node_js
      install:
        - npm install
      before_install:
        - cd senz-client-samples/javascript/
      before_script:
        - cd senz-client-samples/javascript/
      script:
        - npm run lint 
